move otel to a different profile
aws-samples/java-on-aws pull request #221
Opened 2024-01-20 15:38 UTC by yagrxu

Dears,

1. add a new profile `otel-manual` which contains only otel-manual required dependencies.
2. changed otel files to *.opt file
3. add script to rename files back to *.java

test result:
1. compile ok
2. file size from 67 -> 62 MB with command `ll -a`

_-rw-r--r--  1 yagrxu  staff    67M Jan 20 23:25 store-spring-1.0.0.jar
Vs
-rw-r--r--  1 yagrxu  staff    62M Jan 20 23:27 store-spring-1.0.0.jar_

**The change introduces incompatibility in workshop section /observability/others/ADOT Manual Instrumentation**

Best Regards
Yagr

2024-01-20 15:39 UTC, yagrxu commented
@deki @ybezsonov @maschnetwork   Please review the change

2024-01-21 07:22 UTC, deki requested changes
Next time please separate whitespace/ formatting changes (makes it hard to see the real difference)

2024-01-21 07:22 UTC, deki commented on labs/unicorn-store/software/unicorn-store-spring/pom.xml
> +                <plugins>
Plugin definitions from the jvm profile shouldn't be duplicated here. Maven allows multiple profiles to be activated in parallel https://maven.apache.org/guides/introduction/introduction-to-profiles.html#Details_on_profile_activation

2024-01-21 07:22 UTC, deki commented on labs/unicorn-store/software/unicorn-store-spring/pom.xml
> +            <dependencies>
Can you integrate the change I proposed in #130 and use `opentelemetry-spring-boot-starter` to simplify dependency management?

2024-01-22 02:54 UTC, yagrxu commented
@deki  I move the dependency to opentelemetry-spring-boot-starter according to #130 and also combined the profile with jvm to build.

2024-02-02 07:16 UTC, merged

2024-02-02 07:17 UTC, yagrxu commented
I will update the workshop with new content in manual ADOT section - it is already prepared and will be merged
 from feature branch to mainline